module.exports = [
  {
    name: "Aqueduct Racetrack", 
    address: "Racing Hall, 110-00 Rockaway Blvd", 
    city: "South Ozone Park", 
    state: "NY", 
    zip_code: "11420",
    start_date: "2020-12-20", 
    status: "active",
    vaccine_type: "pfizer",
  }, 
  {
    name: "Javits Center", 
    address: "429 11th Avenue", 
    city: "New York", 
    state: "NY", 
    zip_code: "10018",
    start_date: "2020-12-20", 
    status: "active",
    vaccine_type: "Janssen – J & J",
  }, 
  {
    name: "SUNY Stony Brook", 
    address: "100 Nichols Rd", 
    city: "Stony Brook", 
    state: "NY", 
    zip_code: "11794",
    start_date: "2020-12-20", 
    status: "active",
    vaccine_type: "Moderna",
  },   
  {
    name: "SUNY BINGHAMTON", 
    address: "10 Gannett Drive", 
    city: "Johnson City", 
    state: "NY", 
    zip_code: "13790",
    start_date: "2020-12-20", 
    status: "active",
    vaccine_type: "pfizer",
  }, 
]; 